version: "3.8"

networks:
  web:
    driver: bridge

services:
  db:
    image: postgres:14.4
    container_name: rich_app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=countries
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
